### ISSUE TITLE
segfault on start

### ISSUE THREAD

**Issue by elliotttttt** [pip-/simpleGame#1]
Hi, I'm reviewing your resume here at Cerner and noticed the game segfaults almost immediately. Am I building/running it correctly?

```bash
➜  simpleGame git:(master) ✗ gcc game.c
game.c:61:14: warning: format specifies type 'char *' but the argument has type 'char (*)[20]' [-Wformat]
        scanf("%s", &p.name);
               ~~   ^~~~~~~
game.c:73:2: warning: implicit declaration of function 'sleep' is invalid in C99 [-Wimplicit-function-declaration]
        sleep(2);
        ^
2 warnings generated.
➜  simpleGame git:(master) ✗ l
total 56
drwxr-xr-x   7 eh012472  1745752250   238B Mar 23 11:04 .
drwxr-xr-x+ 78 eh012472  1745752250   2.6K Mar 23 11:04 ..
drwxr-xr-x  12 eh012472  1745752250   408B Mar 23 11:04 .git
drwxr-xr-x   5 eh012472  1745752250   170B Mar 23 10:55 Monsters
-rw-r--r--   1 eh012472  1745752250   864B Mar 23 10:55 README.md
-rwxr-xr-x   1 eh012472  1745752250    13K Mar 23 11:04 a.out
-rw-r--r--   1 eh012472  1745752250   5.7K Mar 23 10:55 game.c
➜  simpleGame git:(master) ✗ ./a.out

What is your name? Elliott

Hello Elliott! There is a princess you need to save or
 something you need to find on the other side of the kingdom! But be careful,
[1]    7769 segmentation fault  ./a.out
```

**Comment by pip-** [comment]
Hi Elliott!

Thank you for bringing this issue up to me, and providing all the output information. It appears to be missing the proper library for the sleep command (<unistd.h> on UNIX or <windows.h> on Windows). I will be sure to make and this change in the next day or so.

In the meantime, if you would like to get view some of my other, more recent work, please view my [battleship clone](https://github.com/pip-/battleship/) OR my [minesweeper clone](https://github.com/pip-/minesweeper-js). They have both been recently updated and tested, so be sure to check them out.

**Comment by pip-** [comment]
Fixed! An incorrect file path for the monster's database was hard-coded in the getMonsters function. I also updated the README with a "To Run" section, to help remove doubt on how to run the file.

**Comment by elliotttttt** [comment]
Works. I defeated many wild bunnies and leveled up. Thanks!
